Kudo/react-native-v8

- v8runtime/V8PointerValue.cpp
- v8runtime/V8PointerValue.h
JSI uses PointerValue to allocate String, Object, ...etc,
and JSI controls life cycle itself from invalidate().
JSCRuntime did use JSValueUnprotect() to prevent these values being GCed.
For V8Runtime, we just need to keep they wrapped as v8::Glocal<> and not as weak.
For #2, the `NativeModules.DialogManagerAndroid` will first initialize correctly.
However, during the callback from Alert button clicked, If GC happened, some properties in `NativeModules.DialogManagerAndroid` may not exist and lead to exception.
> V8PointerValue should not be GCed automatically. Fixes #2

- v8runtime/V8Runtime.cpp
Add `global._v8runtime().memory` which will return
```js
{
jsHeapSizeLimit: 767557632,
totalJSHeapSize: 58054528,
usedJSHeapSize: 42930044
}
```
This is pretty much like Chrome's `window.performance.memory`
> Add heap memory statistics 

- v8runtime/V8Runtime.cpp
JSI expects `getPropertyNames()` returned a string array.
However, V8 by default will try to convert the property name as number if possible.
For the case to pass `{ '1': 'numeric_string_key' }` through RN bridge, V8 will crash from unexpected data type that the object property name was being converted to number.
The commit use V8's `v8::KeyConversionMode::kConvertToString` option to convert all property names into string type.
Fixes #10
> Fix JSI crash during convert property numeric names.

- src/patches/build_with_v8.patch
The `$projectDir` for prebuilding v8 RN on the local machine is located at `/path/to/react-native-v8/build/ReactAndroid`.
This project is prebuilding V8 version of RN and publish to npm.
The `ReactAndroid` path may located at `/path/to/react-native-v8/build/ReactAndroid`
And the `v8-android` is installed at `/path/to/react-native-v8/node_modules/v8-android`
But for users who have forked RN source and with this v8 patch, it builds ReactAndroid AAR manually.
The `ReactAndroid` path may located at `/path/to/app/node_modules/react-native/ReactAndroid`
And the `v8-android` is installed at `/path/to/app/node_modules/v8-android`
This PR assumes `$projectDir` is `/path/to/react-native-v8/build/ReactAndroid` as it is now, if the dir does not exist, fallback to …
> fix gradle $projectDir in patch for building with forked RN source

- src/v8runtime/V8Runtime.cpp
- src/v8runtime/V8Runtime.h
as https://github.com/Kudo/react-native-v8/issues/64#issuecomment-834213313 mentioned, jsi `callWithThis` does not work in v8. the reason is relate to [v8 design of call as handler](https://bugs.chromium.org/p/v8/issues/detail?id=1038). alternatively, i turn to use nested call to implement host function.
> fix jsi callWithThis does not work

- src/v8runtime/V8Runtime.cpp
Fix #89 that we did not run v8 foreground tasks
as a `jsi::Runtime`, we didn't have a chance to control the main thread. it looks like the best fit is in `drainMicrotasks` where not ideal but works. i've also done some profile, the time for the while loop takes at maximum 100ms. before there are any better alternatives, i decide to pump the message loop in  `drainMicrotasks`
> Fix v8 foreground tasks not executed

- src/v8runtime/HostProxy.cpp
fix the broken assumption for reanimated's `SharedValue` which may share a HostObject between different JS object
> Fix assertion for multiple JS reference to a HostObject

- android/build.gradle
react-native-v8 version: v1.1.0
I got the following build errors from task `:react-native-v8:mergeDebugAndroidTestJavaResource` ([Detox](https://github.com/wix/Detox) build):
```
* What went wrong:
Execution failed for task ':react-native-v8:mergeDebugAndroidTestJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
> 21 files found with path 'META-INF/MANIFEST.MF' from inputs:
......
```
Add `META-INF` in excludes of packagingOptions will fix this.
> Fix override issue of root packaging options

- android/build.gradle
Adding a pick first rule so that even if CMake adds linked libraries to the project the build will not get affected.
> Add a pick first rule.

- src/v8runtime/V8Runtime.cpp
- src/v8runtime/V8Runtime.h
original implementation in [drainMicrotasks](https://github.com/Kudo/react-native-v8/blob/8e64f7794d2fa5946bb34c5d7bc4098a3806ce8f/src/v8runtime/V8Runtime.cpp#L208-L219) is not good enough. if there are more background tasks, there's still chance to block.
this pr tries to pump the message loop from `requestIdleCallback`
> Pump platform message loop from requestIdleCallback

- src/v8runtime/V8PointerValue.cpp
- src/v8runtime/V8PointerValue.h
when `V8::Global::Reset` in V8PointerValue dtor, we should also protect by a lock. otherwise, there're chances to access dangling pointers.
that should fix the problem @jzxchiang1 had in https://github.com/software-mansion/react-native-reanimated/pull/3132#issuecomment-1112878884
> Fix crash for accessing V8::Global dangling pointer

- src/v8runtime/V8Runtime.cpp
the casting between v8::Value and {String,Object,Symbol} is not necessary
> Optimize shallow clone without casting

- android/mkcodecache.gradle
> Fix mkcodecache issue

- android/src/main/cpp/V8ExecutorFactory.cpp
- src/v8runtime/V8Inspector.cpp
- src/v8runtime/V8Inspector.h
- src/v8runtime/V8PointerValue.cpp
- src/v8runtime/V8Runtime.cpp
- src/v8runtime/V8Runtime.h
- src/v8runtime/V8RuntimeFactory.cpp
- src/v8runtime/V8RuntimeFactory.h
I found out that v8::CpuProfiler keeps some threadLocal stuff and current implementation is calling it from a wrong thread.
It made profiler to return empty profiles. This pr is supposed to fix it.
> Fix v8 profiler 

- src/v8runtime/V8Inspector.cpp
After testing devtools profiler in a large app, we noticed that the profiler stop command would crash with an invalid JSON message error. Upon inspection, what happens is the value of `messageView` when inside the `runOnQueue` closure is no longer the right value, which then fails to parse as JSON in the v8 code.
I think StringView is associated to a v8 scope, which would cause it to be garbage collected at the end of the function. Passing the std::string to the closure instead fixes the problem.
> Fix StringView value when running devtool message on JS thread

- android/build.gradle
from #121 we linked `libjsinspector.so` and AGP sometimes would implicitly add the linked libs and cause duplicated lib issues.
fix #123
> Fix duplicated libjsinspector.so

- .github/workflows/android.yml
- android/CMakeLists.txt
- android/build.gradle
- src/v8runtime/V8Runtime.cpp
- src/v8runtime/V8Runtime.h
add react-native 0.69 support
- react-native 0.69 includes multiple AARs, extract correct AAR for linking.
- react-native 0.69 changes `libfolly_json.so` to `libfolly_runtime.so`.
- react-native 0.69 adds `createPropNameIDFromSymbol` for jsi.
- react-native 0.69 changes boost download location.
- a little refactor for extract so location in building time.
ci passed
Co-authored-by: Ammar Ahmed
> Add react-native 0.69 support

- android/build.gradle
fix #115
the path on windows is not correct:
`C:\DEV\...\node_modules\react-native/ReactCommon/jsiexecutor/jsireact/JSIExecutor.cpp`.
replace file separators to `/` also on windows
> Fix cmake error on windows

- android/build.gradle
> exclude auto linked libfolly_runtime.so

- android/build.gradle
it's not ideal for an app to download 3rd party libraries multiple times.
add `REACT_NATIVE_DOWNLOADS_DIR` environment variable to support custom download location. the way is aligned with [react-native](https://github.com/facebook/react-native/blob/37d0a25cb28879449d89056079c94177c7d2c73f/ReactAndroid/build.gradle#L34-L35)
> Add `REACT_NATIVE_DOWNLOADS_DIR` to specify custom download location

- .github/workflows/android.yml
- android/src/main/cpp/V8ExecutorFactory.cpp
- scripts/lib/patcher.py
- src/v8runtime/V8Inspector.cpp
- src/v8runtime/V8Inspector.h
- src/v8runtime/V8Runtime.cpp
- src/v8runtime/V8Runtime.h
- src/v8runtime/V8RuntimeFactory.h
add react-native 0.70 support
- implement new BigInt interfaces from jsi.h
- [ci] add 0.70 in tests
- [gen_project] set enablesHermes as false
> add react-native 0.70 support

- android/CMakeLists.txt
- android/src/main/cpp/OnLoad.cpp
- android/src/main/java/io/csie/kudo/reactnative/v8/ReactNativeV8Package.java
- android/src/main/java/io/csie/kudo/reactnative/v8/executor/V8Executor.java
- android/src/main/java/io/csie/kudo/reactnative/v8/executor/V8Module.java
- src/v8runtime/V8Runtime.cpp
- src/v8runtime/V8Runtime.h
originally, we pump v8 message loop by `requestIdleCallback` provided by react-native. this will block detox testing because detox detects the app idle state by the internal queue shared with the `requestIdleCallback`. then detox testing will hang.
use the android `Looper.getMainLooper().getQueue().addIdleHandler()` to listen when main runloop is idle and call the c++ code through the native module and runtime executor.
- ci passed
- test compatibility with reanimated
- test compatibility with detox
> alternative solution for pumping v8 message loop

- .prettierrc
- README.md
- package.json
- plugin/build/withV8ExpoAdapter.d.ts
- plugin/build/withV8ExpoAdapter.js
- plugin/src/withV8ExpoAdapter.ts
- yarn.lock
expo-dev-client has bundled reanimated that doesn't support v8. this pr is addressing the issue.
this is a just work and not perfect solution. since expo-dev-client is only for debug build, we could leave jsc libraries only in debug build. originally our config-plugin tries to remove *libjsc\** for all build variants. now the config-plugin only removes jsc in release build. it will append the following statements into *android/app/build.gradle*
```gradle
// @generated begin react-native-v8 - expo prebuild (DO NOT MODIFY) sync-82a32619f78958d84e700d6fd28589aa422b6a61
android {
androidComponents {
onVariants(selector().withBuildType('release')) {
packaging.jniLibs.excludes.add('**/**/libjsc*')
packaging.jniLibs.excludes.add('**/**/libhermes*')
}
}
}
// @generated end react-native-v8
```
> Support expo-dev-client

- android/build.gradle
fix #144
regression from #141 where it introduces _libruntimeexecutor.so_ links but does not exclude it from gradle. that would cause build errors on linux.
> Exclude libruntimeexecutor.so from cmake auto linking

- android/src/main/cpp/OnLoad.cpp
- android/src/main/java/io/csie/kudo/reactnative/v8/executor/V8Module.java
- unregister the listener before native module destroy
- check the runtime from `RuntimeExecutor` is `V8Runtime`
> Improve onMainLoopIdle stability

- src/v8runtime/V8Runtime.cpp
On branch [0.69-v8](https://github.com/Sunbreak/react-native/tree/0.69-v8) of https://github.com/Sunbreak/react-native, when bundleReleaseAar
```
$ ./gradlew :ReactAndroid:bundleReleaseAar
ReactCommon/jsi/v8runtime/V8Runtime.cpp:582:25: error: unused variable 'v8PointerValue' [-Werror,-Wunused-variable]
const V8PointerValue *v8PointerValue =
^
1 error generated.
```
> suppress unused-variable warning

- android/build.gradle
fix #148 
might be a AGP 7 issue: https://issuetracker.google.com/issues/195318431. this pr references the fix from https://github.com/software-mansion/react-native-reanimated/pull/3056 and uses `afterEvaluate` rather than `tasks.whenTaskAdded`.
> Fix missing libv8android.so issue

- .github/workflows/android.yml
- android/CMakeLists.txt
fix #149 
runtimexecutor is a shared library after rn 0.68. for 0.66 and 0.67, reactnativejni includes the symbols.
add 0.66 and 0.67 to ci testing
> Fix build error on RN 0.66 and 0.67

- android/CMakeLists.txt
We have all libs in folder so we shouldn't use systems provided
Fix for https://github.com/Kudo/react-native-v8/issues/157
> Don't use default path when searching for libraries

- .github/workflows/android.yml
- android/CMakeLists.txt
- android/build.gradle
- package.json
- plugin/build/withV8ExpoAdapter.js
- plugin/src/withV8ExpoAdapter.ts
- scripts/lib/patcher.py
- src/v8runtime/HostProxy.cpp
- src/v8runtime/V8Inspector.cpp
- src/v8runtime/V8PointerValue.cpp
- src/v8runtime/V8PointerValue.h
- src/v8runtime/V8Runtime.cpp
- src/v8runtime/V8Runtime.h
- yarn.lock
add react-native 0.71 support
ci passed
> Add react-native 0.71 support

- .github/workflows/android.yml
- .github/workflows/expo-android.yml
- .github/workflows/expo-ios.yml
- android/src/main/java/io/csie/kudo/reactnative/v8/executor/V8ExecutorFactory.java
fixes #168
- this is a regression from #165. i would add the original `getBundleAssetName` back.
- add expo android project ci job
ci passed
> Fix expo integration on android

- .github/workflows/android.yml
- .github/workflows/expo-android.yml
use `google_apis_playstore` api 33 image and it looks like more stable
> [ci] try to make ci test stable

- plugin/build/withV8ExpoAdapter.d.ts
- plugin/build/withV8ExpoAdapter.js
- plugin/src/withV8ExpoAdapter.ts
I'd like to be able to configure if v8 is applied to iOS build. I would expect to be able to configure like this in my expo app.config.js.
```
plugins: [
['react-native-v8', { android: true, ios: false }] 
]
```
Are you open to contributions?
> [feat] add expo plugin config options

- .github/workflows/android.yml
- src/v8runtime/V8Runtime.cpp
- src/v8runtime/V8Runtime.h
Add react-native 0.72 support
- [ci] add react-native 0.72 test
- [v8runtime] fix jsi interface changes from 0.72
---------
Co-authored-by: Ollie <niu15076177821@hotmail.com>
> add react-native 0.72 support

- .github/workflows/expo-ios.yml
- package.json
- plugin/build/withV8ExpoAdapter.js
- plugin/src/withV8ExpoAdapter.ts
- react-native.config.js
considering ios is an advanced and experiment features, it's better to disable ios support by default.
- [expo config-plugins] disable ios by default
- disable ios autolinking when `v8-ios` is not installed
- [ci] explicitly enable ios support for expo config-plugins
> Disable ios by default

- plugin/build/withV8ExpoAdapter.js
- plugin/src/withV8ExpoAdapter.ts
the current plugin breaks on expo sdk 49 (react-native 0.72) because [RNGP will exclude the **libhermes.so** when hermesEnabled=true](https://github.com/facebook/react-native/blob/62e9faefd5f12f5fe6dc88a076ddf7cafda75ee5/packages/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/utils/NdkConfiguratorUtils.kt#L126-L153)
expo-dev-menu requires the hermes in debug build because it does not support v8
update the variant to keep libhermes.so
try the reproducible example from https://github.com/expo/expo/issues/23312
> [plugin] fix support on expo sdk 49 (rn 0.72)

- .github/actions/cleanup-linux-disk-space/action.yml
- .github/workflows/android.yml
- .github/workflows/expo-android.yml
- .github/workflows/expo-ios.yml
- android/CMakeLists.txt
- package.json
- plugin/build/withV8ExpoAdapter.d.ts
- plugin/build/withV8ExpoAdapter.js
- plugin/src/withV8ExpoAdapter.ts
- src/v8runtime/V8Runtime.cpp
- src/v8runtime/V8Runtime.h
- yarn.lock
add react native 0.74 and expo sdk 51 support
- [v8runtime] add stub `setExternalMemoryPressure()`
- [android] fix build error on 0.74
- [ios] update config-plugin to support 0.74 from RCTRootViewFactory
- [ci] update test for react-native 0.74 and expo sdk 51
> feat: add react-native 0.74 support

- .github/workflows/expo-ios.yml
- package.json
- yarn.lock
update outdate dependencies
`yarn upgrade-interactive --latest`
> chore: upgrate dependencies

- RNV8.podspec
- android/CMakeLists.txt
- android/build.gradle
- src/v8runtime/V8Inspector.h
- src/v8runtime/V8Runtime.cpp
- src/v8runtime/V8Runtime.h
react-native 0.74.3 has a new `queueMicrotask` interface to jsi and break existing 0.74.3 build
add no-op `queueMicrotask` implementation since it's used from new architecture. i'll add this when revisiting new architecture support.
> Fix build error from react-native 0.74.3
